import { Question } from "@/lib/types/question-types";

export const dummyQuestions: Question[] = [
    {
        id: "1",
        questionTitle: "Using React Hooks",
        questionText: "lorem ipsum dolor sit amet, consectetur adipiscing elit. How to use React hooks?",
        userId: "user1",
        userAvatarUrl: "/avatars/user1.png",
        status: "answered",
        assignedTo: "expert1",
        createdAt: "2024-06-01T10:00:00Z",
        answers: [
            {
                id: "a1",
                userId: "admin",
                userAvatarUrl: "/avatars/admin.png",
                questionId: "1",
                answerText: "You can use hooks like useState and useEffect in functional components.",
            },
             {
                id: "a2",
                userId: "admin",
                userAvatarUrl: "/avatars/admin.png",
                questionId: "1",
                answerText: "You can use hooks like useState and useEffect in functional components.",
            },
        ],
        tags: [
            { id: "react", name: "Dogma" },
            { id: "hooks", name: "Kenona" },
        ],
    },
    {
        id: "2",
        questionTitle: "TypeScript Overview",
        questionText: "What is TypeScript and why use it?",
        userId: "user2",
        userAvatarUrl: "/avatars/user2.png",
        status: "answered",
        assignedTo: "expert2",
        createdAt: "2024-06-02T11:30:00Z",
        answers: [
            {
                id: "a2",
                userId: "admin",
                userAvatarUrl: "/avatars/admin.png",
                questionId: "2",
                answerText: "TypeScript is a typed superset of JavaScript that helps catch errors early.",
            },
        ],
        tags: [{ id: "typescript", name: "Other" }],
    },
    {
        id: "3",
        questionTitle: "Styling in Next.js",
        questionText: "How to style components in Next.js?",
        userId: "user3",
        userAvatarUrl: "/avatars/user3.png",
        status: "pending",
        createdAt: "2024-06-03T09:15:00Z",
        answers: [],
        tags: [
            { id: "nextjs", name: "Other" },
            { id: "css", name: "Other" },
        ],
    },
    {
        id: "4",
        questionTitle: "useEffect vs useLayoutEffect",
        questionText: "What is the difference between useEffect and useLayoutEffect?",
        userId: "user4",
        userAvatarUrl: "/avatars/user4.png",
        status: "answered",
        assignedTo: "expert3",
        createdAt: "2024-06-04T14:45:00Z",
        answers: [
            {
                id: "a4",
                userId: "admin",
                userAvatarUrl: "/avatars/admin.png",
                questionId: "4",
                answerText: "useLayoutEffect runs synchronously after all DOM mutations, useEffect runs asynchronously.",
            },
        ],
        tags: [
            { id: "react", name: "Dogma" },
            { id: "hooks", name: "Kenona" },
        ],
    },
    {
        id: "5",
        questionTitle: "Fetching Data in React",
        questionText: "How to fetch data in React?",
        userId: "user5",
        userAvatarUrl: "/avatars/user5.png",
        status: "under_review",
        assignedTo: "expert4",
        createdAt: "2024-06-05T16:20:00Z",
        answers: [],
        tags: [
            { id: "react", name: "Dogma" },
            { id: "fetch", name: "Other" },
        ],
    },
    {
        id: "6",
        questionTitle: "Deploying Next.js Apps",
        questionText: "How to deploy a Next.js app?",
        userId: "user6",
        userAvatarUrl: "/avatars/user6.png",
        status: "answered",
        assignedTo: "expert5",
        createdAt: "2024-06-06T12:00:00Z",
        answers: [
            {
                id: "a6",
                userId: "admin",
                userAvatarUrl: "/avatars/admin.png",
                questionId: "6",
                answerText: "You can deploy Next.js apps on Vercel, Netlify, or your own server.",
            },
        ],
        tags: [
            { id: "nextjs", name: "Dogma" },
            { id: "deployment", name: "Kenona" },
        ],
    },
];
